import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Navbar/page'
import Floor from './Navbar/floor'
import Button from './Navbar/button'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Navbar />
        {children}
        <Button />
        <Floor />
      </body>
    </html>
  )
}
